apiVersion: v1
kind: Service
metadata:
  name: test1
spec:
  selector:
    app: test1
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 3001
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: test1
spec:
  selector:
    matchLabels:
      app: test1
  replicas: 1
  template:
    metadata:
      labels:
        app: test1
    spec:
      containers:
      - name: fork8s
        image: conradcorbett/nodejstest:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3001